services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION:-8.3.19}
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    build:
      context: ./
      dockerfile: docker/databases/mysql/Dockerfile
      args:
        - VERSION=${MYSQL_VERSION:-8.0.41}
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-laminasdb_test}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD:-yes}
    volumes:
      - ./test/integration/TestFixtures/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
